Provide a default INSTALLFOLDER.
wixtoolset/wix pull request #435
Opened 2023-07-29 23:06 UTC by barnson

If INSTALLFOLDER is referenced and not defined, define one with reasonable default values.

Implements WIP https://github.com/wixtoolset/issues/issues/7588.

2023-12-26 14:04 UTC, robmen requested changes

2023-12-26 14:04 UTC, robmen commented on src/wix/WixToolset.Core/Link/AddDefaultSymbolsCommand.cs
> +        public IntermediateSection EntrySection { get; }
This `EntrySection` is not used since the FindEntrySectionAndLoadSymbolsCommand was passed in.

2023-12-26 14:04 UTC, robmen commented on src/wix/WixToolset.Core/Link/AddDefaultSymbolsCommand.cs
> +                && !directorySymbols.Any(d => d.Id.Id == WixStandardInstallFolder))
I don't think you need to loop through all the directory symbols. The `this.Find.SymbolsByName` is a dictionary of symbols by their `Id`. You should be able to check the dictionary for the existence of the `WixStandardInstallFolder` symbol.

2023-12-26 14:19 UTC, barnson commented on src/wix/WixToolset.Core/Link/AddDefaultSymbolsCommand.cs
> +            if (referenceSymbols.Any(s => s.SymbolicName == WixStandardInstallFolderReference)
How do we know which sections are referenced before ResolveReferencesCommand?

2023-12-26 23:43 UTC, barnson commented on src/wix/WixToolset.Core/Link/AddDefaultSymbolsCommand.cs
> +                this.AddSymbol(new WixSimpleReferenceSymbol(null, new Identifier(AccessModifier.Global, WixStandardInstallFolder))
This is to `ProgramFiles6432Folder`, not `INSTALLFOLDER`.

2023-12-27 00:03 UTC, barnson commented on src/wix/WixToolset.Core/Link/AddDefaultSymbolsCommand.cs
> +            if (referenceSymbols.Any(s => s.SymbolicName == WixStandardInstallFolderReference)
Given your other suggestions, this isn't a problem for this PR. Crossing my fingers for future.

2023-12-29 18:35 UTC, robmen requested changes
Subtle things that if resolved, I think this is good to go.

2023-12-29 21:30 UTC, barnson commented on src/wix/WixToolset.Core/Link/AddDefaultSymbolsCommand.cs
> +                // first reference as the "canonical" reference for source line numbers.
Bad comment from merge. These don't come from the stdlib, so I gave them a different name.

2023-12-30 06:26 UTC, robmen approved these changes

2023-12-30 20:59 UTC, merged

2023-12-30 20:59 UTC, barnson commented
W00t.