Introduce early exception for overlength Windows Installer table name
wixtoolset/wix pull request #558
Opened 2024-08-05 11:46 UTC by bevanweiss

Introduces checks on Merge Modules and Products for overlength table names (> 31 characters).

Closes wixtoolset/issues#8645

2024-09-28 21:43 UTC, barnson requested changes
A couple of nitpicks.

2024-09-28 21:43 UTC, barnson commented on src/api/wix/WixToolset.Data/ErrorMessages.cs
> +        public static Message OverlengthTableNameInMergeModule(SourceLineNumber sourceLineNumbers, string tableName)
This message isn't necessary; the second one will suffice (and I prefer its message too).

2024-09-28 21:43 UTC, barnson commented on src/api/wix/WixToolset.Data/ErrorMessages.cs
> +            return Message(sourceLineNumbers, Ids.OverlengthTableNameInProduct, "The table name '{0}' is invalid because the table name exceeds 31 characters in length. https://learn.microsoft.com/en
Add `For more information, see: <url>`.

2024-12-25 03:28 UTC, robmen approved these changes

2024-12-25 03:31 UTC, barnson approved these changes

2024-12-26 13:54 UTC, robmen approved these changes

2024-12-26 14:40 UTC, merged