Fallback to per-machine appdata folder when per-user appdata folder is not found.
wixtoolset/wix pull request #567
Opened 2024-09-13 15:10 UTC by cornerbowlsoftware

This update is an attempt to move past the "Failed to find local per-user appdata directory." when not found.  Issue: [https://github.com/wixtoolset/issues/issues/8715](https://github.com/wixtoolset/issues/issues/8715)

2024-09-13 15:55 UTC, cornerbowlsoftware commented
I have read the CLA Document and I hereby sign the CLA

2024-09-16 13:47 UTC, cornerbowlsoftware commented
@barnson can you please look at this PR when you have time?

2024-09-17 02:27 UTC, barnson requested changes
I don't think this is the right change. The unelevated engine will always fail when caching to a per-machine path so it's not really a fallback. Off the top of my head, the lack of a per-user cache path should fail as quickly as possible when a per-user cache is needed.

2024-09-17 02:43 UTC, cornerbowlsoftware commented
> I don't think this is the right change. The unelevated engine will always fail when caching to a per-machine path so it's not really a fallback. Off the top of my head, the lack of a per-user cache path should fail as quickly as possible when a per-user cache is needed.

@barnson In my case, I am only installing per-machine and the GMSA account that is remote installing does not have a per-user cache causing the engine to fail.  Can we leave the values uninitialized then when they are needed for users installing per-user, fail when the values are read?

2024-09-18 00:24 UTC, barnson commented
That's what I'm thinking. During planning, the engine knows if a per-user cache location is needed so if the path is NULL, throw an error. That prevents an access denied failure after elevating.

2024-09-18 00:38 UTC, cornerbowlsoftware commented
@barnson I can certainly help with the task, however it seems like you are the best person for it, and I suspect this is a two liner, one line to ignore the missing value in cache.cpp.CacheInitialize then another to throw the error in cache.cpp.GetRootPath but you are the expert. Please let me know if there is anything I can do to either implement it or help out.  Thanks for looking at this and all your work on this project. I am grateful I no longer have to use InstallShield.

2024-09-18 01:42 UTC, barnson commented
OK, then I'll mark this `up for grabs` so interested parties know it's available to work on.

2024-09-18 01:42 UTC, closed without merging